### ISSUE TITLE
can you add V3 tagger

### ISSUE THREAD

**Issue by Varkilister** [DEX-1101/kohya-trainer#2]
Please update the tagger, add V3 tagger

  | SWINV2_MODEL_DSV3_REPO = "SmilingWolf/wd-swinv2-tagger-v3"
  | CONV_MODEL_DSV3_REPO = "SmilingWolf/wd-convnext-tagger-v3"
  | VIT_MODEL_DSV3_REPO = "SmilingWolf/wd-vit-tagger-v3"

https://huggingface.co/SmilingWolf/wd-swinv2-tagger-v3
https://huggingface.co/SmilingWolf/wd-convnext-tagger-v3
https://huggingface.co/SmilingWolf/wd-vit-tagger-v3

**Comment by DEX-1101** [comment]
i try already it but i have no luck, it always failed when trying to tagging the image

**Comment by DEX-1101** [comment]
added a148a88ca365dcdaa8f9f86dff5fd6645a083458
