### ISSUE TITLE
Jax Issue

### ISSUE THREAD

**Issue by propergurl** [DEX-1101/kohya-trainer#3]
By this morning, xformers 0.0.25 not work and display jax issue as below :
![WhatsApp Image 2024-04-09 at 04 53 47_29d2b69f](https://github.com/DEX-1101/kohya-trainer/assets/156979959/2cabac7b-3a22-470e-a001-a5409a6aa14a)

any suggest to fix this issue? thank you.

**Comment by DEX-1101** [comment]
55b4aab should be fixed
