### ISSUE TITLE
Do you have sd 1.5 lora training?

### ISSUE THREAD

**Issue by upright2003** [DEX-1101/kohya-trainer#4]
I used this version to train sd 1.5 lora, but it doesn't work today,
https://github.com/Linaqruf/kohya-trainer
Then I went to github and the author found that it had been sealed and could not be discussed.
I would like to ask if you have updated sd 1.5 colab?

I have a problem https://colab.research.google.com/drive/1zG6CLlNAUvDUHzvgY4hGkQvtdcRBsPiN#scrollTo=lsx2bk0yrFT2

In 4.3 TypeError: '<' not supported between instances of 'TorchVersion' and 'Version'
Do you know how to solve it? Thank you!

**Comment by DEX-1101** [comment]
sadly i am not playing sd1.5 anymore, if you're looking the update one, you can try [this](https://github.com/hollowstrawberry/kohya-colab/blob/main/Lora_Trainer.ipynb)

**Comment by upright2003** [comment]
thank you!!

**Comment by upright2003** [comment]
Refer to your colab file 1.1
I added
` !pip -q install prodigyopt==1.0 jax==0.4.23 jaxlib==0.4.23`
You can continue to step 4.3, thank you!
