### ISSUE TITLE
how to use WD tagger V3?

### ISSUE THREAD

**Issue by Nurhuu** [DEX-1101/kohya-trainer#7]
I've clicked on it but the txt format doesn't appear.

**Comment by DEX-1101** [comment]
![Screenshot 2024-11-04 062747](https://github.com/user-attachments/assets/d6a8d5e3-885e-4c8a-9a3f-16c8254714ca)
any screenshoot/proof?
i just test it and it's working fine

**Comment by Nurhuu** [comment]
> ![Screenshot 2024-11-04 062747](https://private-user-images.githubusercontent.com/71503763/382612836-d6a8d5e3-885e-4c8a-9a3f-16c8254714ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDAwMjAsIm5iZiI6MTczMDY5OTcyMCwicGF0aCI6Ii83MTUwMzc2My8zODI2MTI4MzYtZDZhOGQ1ZTMtODg1ZS00YzhhLTlhM2YtMTZjODI1NDcxNGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA1NTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Nzc3OGFhMTVhY2Y3ZGNmYWUyNDkyZGVkZDZhNzRhNGZlYzMyMzE1NmUyYWRkNDQwNDNhMmJlYTRiMGRmYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X2xMA0VS04uPaiJ12XrkF-XLzZ6Aa9VdMFzAw7Oy9_M) any screenshoot/proof? i just test it and it's working fine



> ![Screenshot 2024-11-04 062747](https://private-user-images.githubusercontent.com/71503763/382612836-d6a8d5e3-885e-4c8a-9a3f-16c8254714ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDAwMjAsIm5iZiI6MTczMDY5OTcyMCwicGF0aCI6Ii83MTUwMzc2My8zODI2MTI4MzYtZDZhOGQ1ZTMtODg1ZS00YzhhLTlhM2YtMTZjODI1NDcxNGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA1NTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Nzc3OGFhMTVhY2Y3ZGNmYWUyNDkyZGVkZDZhNzRhNGZlYzMyMzE1NmUyYWRkNDQwNDNhMmJlYTRiMGRmYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X2xMA0VS04uPaiJ12XrkF-XLzZ6Aa9VdMFzAw7Oy9_M) any screenshoot/proof? i just test it and it's working fine

it's working, thank you.
