### ISSUE TITLE
Bucketing does not end

### ISSUE THREAD

**Issue by younyokel** [DEX-1101/kohya-trainer#9]
Tried this fork, I really hope you can remake it. Unfortunately, when bucket resolution was set to 1024, it errored with "tcmalloc: large alloc 1610612736 bytes == 0x56e6d1a10000". Tried 512, but it is stuck or too slow?

**Comment by DEX-1101** [comment]
could you provide a way to reproduce it? maybe you use too many image
i use around 50 images and still working

**Comment by younyokel** [comment]
> could you provide a way to reproduce it? maybe you use too many image i use around 50 images and still working

i tested with free colab and 71 images

![image](https://github.com/user-attachments/assets/2391e574-86f3-4640-af87-090f382aa312)

**Comment by DEX-1101** [comment]
![Screenshot_7](https://github.com/user-attachments/assets/f634fc06-b05d-475b-9efd-6dc2bacf9b5a)
so it's happend if you use more than 50 images looks like.
try again and remove this line code : 
![Screenshot_140](https://github.com/user-attachments/assets/3dc96b83-5108-4ee4-b524-efef176c29c2)
and tell me if it working or not and not causing new issue, i will push the fix later

**Comment by younyokel** [comment]
> and tell me if it working or not and not causing new issue, i will push the fix later

![image](https://github.com/user-attachments/assets/fcfe2ddb-d433-4fb1-b5b2-65f8b3f52b7f)

Definitely fixed the alloc issue but it's now stuck on 14%, been waiting for over 10 minutes.

**Comment by Nurhuu** [comment]
try using this old version, just need to replace xformers to xformers==0.0.28.post2

https://colab.research.google.com/github/monsterhunters/Lora-Training-GUI/blob/main/kohya_LoRA_trainer_XL_pony_v2.ipynb#scrollTo=_u3q60di584x

**Comment by DEX-1101** [comment]
can be a problem with you dataset/colab, mine just fine with over 100 images
maybe i could try if you want to share it

**Comment by DEX-1101** [comment]
7ae7b3bcbefdd85280790f899cc9fa3214a710ec
